/* tslint:disable */
/* eslint-disable */
/**
 * Sample OpenAPI -- IADI 2021/22
 * This is a sample for the openAPI lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BookListDTO
 */
export interface BookListDTO {
    /**
     * 
     * @type {number}
     * @memberof BookListDTO
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof BookListDTO
     */
    title?: any;
    /**
     * 
     * @type {Array&lt;AuthorsBookDTO&gt;}
     * @memberof BookListDTO
     */
    authors?: any;
    /**
     * 
     * @type {Array&lt;ImageDTO&gt;}
     * @memberof BookListDTO
     */
    images?: any;
}
