/* tslint:disable */
/* eslint-disable */
/**
 * Sample OpenAPI -- IADI 2021/22
 * This is a sample for the openAPI lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SessionDTO
 */
 export interface SessionDTO {
    /**
     * 
     * @type {string}
     * @memberof SessionDTO
     */
    username?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SessionDTO
     */
    roles?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionDTO
     */
     jwt?: any;
}